name: Docker Image CI 1.0.$GITHUB_RUN_ID

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  imagename: whoha4242/liatrio-exercise
  tag: 1.0.$GITHUB_RUN_ID
  dockeruser: whoha4242
  # NOTE: You must include a secret in your repo's settings to contain your docker user's password or change docker auth methods
  dockerpwd: ${{secrets.dockerpassword}}

jobs:

  build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.imagename}}:${{env.tag}}
    - name: Add latest tag
      run: docker tag ${{env.imagename}}:${{env.tag}} ${{env.imagename}}:latest
    - name: Docker Login
      run: docker login -u ${{env.dockeruser}} -p ${{env.dockerpwd}}
    - name: Push the Docker image versioned tag
      run: docker push ${{env.imagename}}:${{env.tag}}
    - name: Push the Docker image latest tag
      run: docker push ${{env.imagename}}:latest