name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  imagename: whoha4242/liatrio-exercise
  tag: 1.0.$GITHUB_ACTION

jobs:

  build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.imagename}}:${{env.tag}}
    - name: Add latest tag
      run: docker tag ${{env.imagename}}:${{env.tag}} ${{env.imagename}}:latest
    - name: Push the Docker image versioned tag
      run: docker push ${{env.imagename}}:${{env.tag}}
    - name: Push the Docker image latest tag
      run: docker push ${{env.imagename}}:latest